import { Player } from 'types/Player';

export const createFakePlayer = (props?: Partial<Player>): Player => ({
  agreementTermsAccepted: false,
  externalPlayerId: '123',
  playerId: 12,
  currency: 'EUR',
  firstName: 'testFirstName',
  lastName: 'testLastName',
  displayName: 'testDisplayName',
  gender: 'male',
  phoneCode: '+372',
  phoneNumber: '55555555',
  isVerified: false,
  countryId: 'EE',
  playerPermissions: [],
  zipCode: '12012',
  email: 'test@test.com',
  dateOfBirth: '1990-12-12',
  languageId: 'en',
  street: 'test',
  subscriptionEmailEnabled: false,
  subscriptionSmsEnabled: false,
  consentPhone: false,
  consentPostmail: false,
  consentPush: false,
  externalToken: 'externalToken',
  ...props,
});
